### PR TITLE
bit.ly links how are you allowed to make kodi addons?

### PR DESCRIPTION
**Pull request by I-Cat**
Odd I see all the bit.ly links and hidden donation scripts , how are you allowed to make kodi addons?

### CODE REVIEW

**Comment by krustyreturns** [comment]
?  I have a donation button for serverwmc on its webpage, but its not hidden.  I do use bitly links to distribute serverwmc.  Are either of these a rules violation?

**Comment by DaVukovic** [comment]
@krustyreturns 
No it's not a rule violation and @I-Cat is also not a TeamKodi member. So I wouldn't pay to much attention of what he's saying. He spammed our git as well and we already blocked him (AFAIK). 

I took a look and I couldn't find anything offending on the download page. So that seems to be totally fine as well as donations to your project are. 

For the future, if you have any questions in regard of what is allowed (and probably what not) feel free to contact TeamKodi whenever you like. But currently there seems to be no need to. 

Have fun and thanks for your add-on.

**Comment by krustyreturns** [comment]
Thanks for letting me know.

**Comment by I-Cat** [comment]
o okay i didn't know it was allowed.

**Pull request closed without merging**
